"""Initial

Revision ID: 37f95c6306e9
Revises: 
Create Date: 2023-12-05 20:54:42.314519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37f95c6306e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('lang_selected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_contracts',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BIGINT(), nullable=False),
    sa.Column('contract_name', sa.String(length=100), nullable=False),
    sa.Column('contract_address', sa.String(length=100), nullable=False),
    sa.Column('contract_description', sa.String(length=100), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_contracts')
    op.drop_table('users')
    # ### end Alembic commands ###
